<template>
  <div>
    <SoluHeaderBar></SoluHeaderBar>
    <main>
      <section>
        <SoluApply></SoluApply>
        <Solusence></Solusence>
      </section>
    </main>
    <FooterBar></FooterBar>
  </div>
</template>
